config/routes.rb
Rails.application.routes.draw do
  resources :polaroids
  devise_for :users
  root to: 'pages#home'
  get '/photography', to: 'pages#photography'
 get '/cinematography', to: 'pages#cinematography'
 get '/panchito', to: 'pages#panchito'
  get '/contact', to: 'pages#contact'
  get '/archivos', to: 'pages#records'
   get 'download_pdf', to: "pages#download_pdf"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/polaroid.rb
class Polaroid < ApplicationRecord
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :cinematography, :photography, :contact, :records, :download_pdf]

  def home
  end

  def cinematography
  end

  def photography
    @polaroids = Polaroid.all
  end

  def records

  end

  def download_pdf
    send_file "#{Rails.root}/app/assets/records/naturecolorbyfranciscodutary.cube.zip", type: "application/zip", x_sendfile: true
  end

  def contact
  end

  def panchito
    @polaroids = Polaroid.all
  end

end

app/controllers/polaroids_controller.rb
class PolaroidsController < ApplicationController
  before_action :set_polaroid, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:show]

  # GET /polaroids
  # GET /polaroids.json
  def index
    @polaroids = Polaroid.all
  end

  # GET /polaroids/1
  # GET /polaroids/1.json
  def show
  end

  # GET /polaroids/new
  def new
    @polaroid = Polaroid.new
  end

  # GET /polaroids/1/edit
  def edit
  end

  # POST /polaroids
  # POST /polaroids.json
  def create
    @polaroid = Polaroid.new(polaroid_params)

    respond_to do |format|
      if @polaroid.save
        format.html { redirect_to @polaroid, notice: 'Polaroid was successfully created.' }
        format.json { render :show, status: :created, location: @polaroid }
      else
        format.html { render :new }
        format.json { render json: @polaroid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polaroids/1
  # PATCH/PUT /polaroids/1.json
  def update
    respond_to do |format|
      if @polaroid.update(polaroid_params)
        format.html { redirect_to @polaroid, notice: 'Polaroid was successfully updated.' }
        format.json { render :show, status: :ok, location: @polaroid }
      else
        format.html { render :edit }
        format.json { render json: @polaroid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polaroids/1
  # DELETE /polaroids/1.json
  def destroy
    @polaroid.destroy
    respond_to do |format|
      format.html { redirect_to polaroids_url, notice: 'Polaroid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_polaroid
      @polaroid = Polaroid.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def polaroid_params
      params.require(:polaroid).permit(:title, :description, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Francisco Dutary</title>
  <meta name="description" content="Francisco Dutary - FILMS|PHOTOS">
  <meta name="keywords" content="Photos, Art, Artist, HD photos, Video">
  <meta name="author" content="Leo">
  <meta property=”og:title” content=”FranciscoDutary”/>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
<link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
</head>
<body class="Site">
  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
  <main class="Site-content">
    <div class="content">
      <%= yield %>
    </div>
  </main>
  <%= render 'shared/footer' %>
  <%= javascript_include_tag 'application' %>

  <%= javascript_pack_tag 'application' %>
</body>
</html>

app/views/pages/cinematography.html.erb
<div class="container" style="padding-top: 150px">
  <h2 class="text-center" style="color: white; font-family: 'Raleway', sans-serif;"> CINEMATOGRAPHY</h2>
  <br>
  <hr>
  <div class="text-center">

    <iframe  src="https://www.youtube.com/embed/MonGA9yY-Oo" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

    <iframe  src="https://www.youtube.com/embed/3rYhwVAF04o" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <br>
    <iframe  src="https://www.youtube.com/embed/_RlX6f8E9gs" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <br>
    <iframe src="https://www.youtube.com/embed/QG4Q3BRABg4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <br>
    <iframe  src="https://www.youtube.com/embed/TwuxA5HhvSw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <br>
    <iframe src="https://www.youtube.com/embed/ng0vPEp2nHA" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </div>
  <hr>
</div>
<br>
<br>
<br>

app/views/pages/contact.html.erb
<br>
<br>
<br>
<div class="about" style="padding-top: 100px;">
 <div class="container">
  <hr>
  <div class="row">
    <div class="col-xs-12 col-sm-6 text-center frame padded">
      <%= image_tag("logo.png")%>
    </div>
    <div class="col-xs-12 col-sm-6">
     <ul class="list-unstyled padded ">
      <div style="color: white;">
      <h3>Francisco Dutary</h3>
      <br>
      <h4><i class="fas fa-envelope"></i> fdutary@gmail.com</h4>
      <a href="https://www.instagram.com/franciscodutary/" style="color: white"><h4><i class="fab fa-instagram"></i> @fanciscodutary</h4></a>
      <h4><i class="fas fa-phone"></i> +507 6666-1442</h4>
      <br>
      <h3 class="btn btn-bro" style="border-radius: 50px; color: black;"><a href="https://api.whatsapp.com/send?phone=+5076666-1442" style="color: black;">Contactame</a></h3>

      </div>

    </ul>
  </div>
</div>
<hr>
</div>
<br>
<br>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.6) 0%, rgba(0,0,0,0.7) 50%), url('<%= image_path('bannerfd.gif')%> '); background-position: center;">
  <div>
    <div class="hidden-xs hidden-sm">
      <h2 style="font-family: 'Raleway', sans-serif;">FRANCISCO DUTARY</h2>
    </div>
    <br>
    <p>FILMS | PHOTOS</p>
    <br>
    <i class="fa fa-angle-double-down symbols" aria-hidden="true"></i>

  </div>

</div>

<div class="container" style="padding-top: 150px;">
  <h4 class="text-center" style="color:white; font-family: 'Raleway', sans-serif; font-weight: lighter;">Soy un filmmaker panameño y me apasiona contar historias atrapando momentos con mi cámara.</h4>
</div>
<br>
<div class=" container">
  <br>
  <div class="text-center " style="padding-bottom: 150px">
    <hr style="background-color: white: ">
    <iframe width="560" height="315" src="https://www.youtube.com/embed/GSwfOhd8CUw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <hr>
  </div>
</div>
<div class="banner2" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.3) 0%, rgba(0,0,0,0.3) 50%), url('<%= image_path('fotosbanner.jpg')%> '); background-position: center;">
  <div>
   <%= link_to photography_path do %>
   <h1 class="text-center" style="color: white; text-decoration: none;  font-family: 'Raleway', sans-serif;"> PHOTOGRAPHY</h1>
   <% end %>

 </div>

</div>
<div class="container" style="padding-top: 150px;">
  <h4 class="text-center" style="color:white; font-family: 'Raleway', sans-serif; font-weight: lighter;">"Más que amar a la naturaleza se trata de conectarse con ella”
  </h4>
</div>
<br>
<div class=" container">
  <br>
  <div class="text-center " style="padding-bottom: 150px">
    <hr style="background-color: white: ">
    <iframe width="720" height="400" src="https://www.youtube.com/embed/jKUbFNVB-7c" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <br>
    <hr>
  </div>
</div>
<div class="banner2" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.3) 0%, rgba(0,0,0,0.3) 50%), url('<%= image_path('videosbanner.jpg')%> '); background-position: center;">
   <%= link_to cinematography_path do %>
  <h1 class="text-center" style="color: white; text-decoration: none;  font-family: 'Raleway', sans-serif;">
    CINEMATOGRAPHY
  </h1>
  <% end %>

</div>

<div class="container" style="padding-top: 150px;">
  <h4 class="text-center" style="color:white; font-family: 'Raleway', sans-serif;font-weight: lighter;">Descubrí mi pasión por el cine explorando lugares mágicos en Panamá, escalando montañas y haciendo deportes extremos.
  </h4>
</div>
<div class=" container">
  <br>
  <div class="text-center " style="padding-bottom: 150px">
    <hr style="background-color: white: ">

    <iframe width="560" height="315" src="https://www.youtube.com/embed/h6DhYhQvGB4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <br>
    <hr>
  </div>
</div>

app/views/pages/panchito.html.erb
<div class="container" style="padding-top: 150px">
  <h1 class="text-center" style="color: white; font-family: 'Raleway', sans-serif;"> Administrador</h1>
  <br>
  <hr>
  <div class=" text-center">
   <h4 style="color: white;">Photos</h4>

  <% @polaroids.each do |polaroid| %>
<br>
  <p style="color: white;"><%= polaroid.title %> | <%= link_to 'Show', polaroid %> | <%= link_to 'Edit', edit_polaroid_path(polaroid) %> | <%= link_to 'Destroy', polaroid, method: :delete, data: { confirm: 'Are you sure?' } %></p>

  <% end %>
  <br>
    <%= link_to 'New trip', new_polaroid_path, class: "btn btn-bro" %>
  <br>
  </div>
  <hr>
</div>

app/views/pages/photography.html.erb
<div class="container" style="padding-top: 150px">
  <h2 class="text-center" style="color: white; font-family: 'Raleway', sans-serif;"> PHOTOGRAPHY</h2>

  <br>
  <hr>
<br>
    <% @polaroids.each do |polaroid| %>
    <div class="col-xs-12 text-center" style="">
      <%= link_to polaroid_path(polaroid) do %>
      <div class="resposive">
      <%= cl_image_tag polaroid.photo.key, height: 300, class: "img-fluid", crop: :fill %>
      </div>
      <p style="color: white; font-family: 'Raleway', sans-serif;"><%= polaroid.title %></p>
      <% end %>
    </div>
    <% end %>
  <hr>
</div>
<br>
<br>
<br>

app/views/pages/records.html.erb
<div class="container" style="padding-top: 150px;">
  <h1 class="text-center" style="color:white; font-family: 'Raleway', sans-serif; font-weight: lighter;">Archivos Descargables</h1>
  <br>
  <hr>
  <br>
  <div class="text-center">
  <h3 style="color: white;">Lut</h3>
  <p style="color: white;">Nature Color by Francisco Dutary</p>
  <%= link_to download_pdf_path  do%>
  <p>Download <i class="fas fa-download"></i></p>
  <% end %>
  </div>
  <br>
  <hr>
  <br>
</div>

app/views/polaroids/_form.html.erb
<%= simple_form_for(@polaroid) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-bro" %>
  </div>
<% end %>

app/views/polaroids/edit.html.erb
<div class="container" style="padding-top: 150px; color: white;">
<h1>Editing Polaroid</h1>

<%= render 'form', polaroid: @polaroid %>

<%= link_to 'Show', @polaroid %> |
<%= link_to 'Back', polaroids_path %>
</div>

app/views/polaroids/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Polaroids</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @polaroids.each do |polaroid| %>
    <tr>
      <td><%= polaroid.title %></td>
      <td><%= polaroid.description %></td>
      <td><%= cl_image_tag polaroid.photo.key, height: 300, width: 400, crop: :fill %></td>
      <td><%= link_to 'Show', polaroid %></td>
      <td><%= link_to 'Edit', edit_polaroid_path(polaroid) %></td>
      <td><%= link_to 'Destroy', polaroid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>



    <% @polaroids.each do |polaroid| %>

 <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path polaroid.photo.key %>')">
  Breakfast
</div>

    <% end %>


<br>
<br>
<br>

<%= link_to 'New Polaroid', new_polaroid_path %>

app/views/polaroids/new.html.erb
<div class="container" style="padding-top: 150px; color: white;">
<h1>New Polaroid</h1>

<%= render 'form', polaroid: @polaroid %>

<%= link_to 'Back', polaroids_path %>
</div>

app/views/polaroids/show.html.erb
<div class="container text-center" style="padding-top: 150px; padding-bottom: 50px;">
  <h2 style="color: white; font-family: 'Raleway', sans-serif;"> <%= @polaroid.title %></h2>
  <br>
  <hr>
  <br>
  <div class="img-res">
    <%= cl_image_tag @polaroid.photo.key, height: 450 %>
  </div>
  <br>
  <p style="color: white; font-family: 'Raleway', sans-serif;">  <%= @polaroid.description %></p>
  <hr>
  <br>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div style="">
  <div class="footer2">
    <div class="container text-center " style="padding-top: 8px; padding-bottom: 8px;" >
      <a href="http://www.leonardoluxburg.com">
        <%= image_tag "lllogo.png" %>
      </a>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag('logo.png') %>
  <% end %>

 <div class="navbar-wagon-item hidden-md hidden-lg">
 <div class="dropdown">
  <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown" style="color: white !important"></i>
  <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
       <li> <p><%= link_to "Home", root_path, class: "navbar-wagon-item navbar-wagon-link"%></p></li>
         <li><p><%= link_to "Film", cinematography_path, class: "navbar-wagon-item navbar-wagon-link"%></p></li>
       <li><p><%= link_to "Photos", photography_path, class: "navbar-wagon-item navbar-wagon-link"%></p></li>
       <li><p><%= link_to "Descargables", archivos_path, class: "navbar-wagon-item navbar-wagon-link"%></p></li>
        <li><p><%= link_to "Contact", contact_path, class: "navbar-wagon-item navbar-wagon-link"%></p></li>
       <% if current_user %>
       <%= link_to destroy_user_session_path, method: :delete do %>
       <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
       <% end %>
       <% end %>
     </ul>
 </div>
</div>
</div>